### ISSUE TITLE
Invalid code in PCHost.gd

### ISSUE THREAD

**Issue by MisterMisclick** [daz-b-like/ProCam2D_Godot4.x#1]
Current code causes failure to compile due to PCHost.gd line 194 in current code base:
`_cur_offset = _cur_offset.linear_interpolate(_target_offset, _exp_smoothing(offset_duration, delta))`

I believe this should be:
`_cur_offset = _cur_offset.lerp(_target_offset, _exp_smoothing(offset_duration, delta))`

**Comment by daz-b-like** [comment]
### **Fixed!**
Thank you for pointing this out. I must have left it out when porting the plugin from Godot 3.x to 4.x
