### ISSUE TITLE
Manually zooming camera (<1) breaks target multiple objects

### ISSUE THREAD

**Issue by MisterMisclick** [daz-b-like/ProCam2D_Godot4.x#2]
Manually zooming camera in editor (<1) breaks targeting on multiple objects.

**To Reproduce**
I believe this bug exists as long as you attempt to target multiple objects with a zoom of less than 1 on the ProCam. More thorough details of minimum reproduction below:

- Create new project: TestScene
- Add CharacterBody2D: "Player" with following code:
```
extends CharacterBody2D

const SPEED = 300.0

func _ready():
	ProCam.set_tmo(true)


func _physics_process(delta):
	var direction = Input.get_axis("ui_left", "ui_right")
	if direction:
		velocity.x = direction * SPEED
	else:
		velocity.x = move_toward(velocity.x, 0, SPEED)

	move_and_slide()
```
- Add sprite to player for visibility
- Add ProCam and PCTrackPoint. Enable PCTrackPoint. Assign player as target for ProCam.
- Add second sprite to scene with PCTrackPoint. Enable the second PCTrackPoint. It should be noted that if you run the scene at this point it functions as intended, keeping both PCTrackPoints on the screen.
- Zoom the ProCam to a number less than 1. (I discovered this using 0.3 but have also tested 0.5)

If you run the scene under these conditions both PCTrackPoints leave the scene and the space between them remains on the scene.

**Expected behavior**
All PCTrackPoints remain on scene regardless of camera zoom. The camera should re-zoom to fit all PCTrackPoints.

**Desktop (please complete the following information):**
 - OS: Windows
 - Godot Version 4.2.2
 - Plugin Version 0.2

If necessary I can upload my test scene for context. Apologies if this is user error, I am relatively inexperienced. I did try to thoroughly solve the problem on my own prior to making this account to report the bug(s). I love the plugin and appreciate all the work you have put into it!

**Comment by daz-b-like** [comment]
### **Fixed!**
The bug is fixed for zoom-ins (<1) and zoom-outs (>1). Thank you so much for reporting. You can get the updated version from [here](https://github.com/daz-b-like/ProCam2D_Godot4.x/archive/66239343a870891a8505cb040a067ec38901790d.zip), since the one on the asset library might take long to update. Happy coding!
