### ISSUE TITLE
Setting camera limits breaks target multiple objects

### ISSUE THREAD

**Issue by MisterMisclick** [daz-b-like/ProCam2D_Godot4.x#3]
**Describe the bug**
Track multiple objects malfunctions when camera limits are set to small areas (<1000x1000). Camera appears to only zoom in and out but not move relative to positions. Sporadically occurs seemingly based on positions of PCTrackPoints _on_ready.

**To Reproduce**
Same steps as issue regarding zoom-in tracking, however this time leave zoom at 1 and set limits. For testing purposes I did LL -400, RL 400, TL -400, and BL 400, this configuration experienced the issue. The issue also appears if you set limits to LL 0,  RL <1500, TL 0, BL < 1000. The closer you move one of the PCTrackingPoints to the edge the less well the tracking works, to the point of breaking down completely (sometimes before a PCTrackingPoint reaches the limit). The bug becomes more obvious from my experience when one of the PCTrackPoints is near the limit when the scene is initialized. Once this occurs the camera no longer follows any of the PCTrackingPoints well. The issues go away entirely if ProCam.set_tmo(false).

**Expected behavior**
Camera defaults to tracking assigned target when PCTrackingPoint(s) cannot be followed. 

**Desktop (please complete the following information):**
 - OS: Windows
 - Godot Version 4.2.2
 - Plugin Version 0.2

**Additional context**
For context I work with pixel art, with small tiles and assets (typically 16x16) so my scenes rarely get over 1000x1000 pixels. The limits work great when set_tmo(false).
Also I just wanted to say I love this plugin! The functionality is amazing.

**Comment by daz-b-like** [comment]
### **Fixed!**
I refactored limiting logic to work as expected. Kindly give feedback if you still experience any errors. And thanks again for reporting. I'm working on an update so feel free to make any bug report, feature requests or suggestion. Thanks again.
Grab the updated version [here](https://github.com/daz-b-like/ProCam2D_Godot4.x/archive/b4da8c46ce0efb5b77dcd29d9ac39c41d3b41ee0.zip)
