### ISSUE TITLE
PCam does not update Room constraints for instantiated rooms during runtime.

### ISSUE THREAD

**Issue by HiIAmBarney** [daz-b-like/ProCam2D_Godot4.x#4]
**Describe the bug**
Perhaps this is more of an oversight or not intended feature but it would be nice to have regardless.
When a PCamRoom node is a child of a Scene (in this case a Level) that gets instantiated during runtime, the PCam does not get notified of a Room Change.

**To Reproduce**
1. Add PCam to Main Scene
2. Add (and properly set-up) PCamRoom to a Level Scene
3. Have the Level Scene instantiated as a Child of the Main Scene (And sibling to PCam Node) during runtime
4. When the Level Scene is instantiated, PCam does not follow Room Constraints.

**Expected behavior**
It would be neat to have the Camera get notified about Rooms added to the Tree during runtime, similar to how it works when the Room is already related to PCam in the Scene Tree during Editor Time.
This way, the entire Level doesn't have to be in one massive scene, which also allows smoother integration with other Plugins (such as MetSys) or Scene Transition Tools.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Godot Version 4.3
 - Plugin Version Godot 4.x version 0.2(latest)

**Additional context**
I tried to combine PCam with MetSys and since MetSys is particularly picky about how it handles room transitions (to correctly draw the Minimap, etc.) this would be a perfect feature to have.

**Comment by daz-b-like** [comment]
Hello @HiIAmBarney . Thanks for pointing that out. I've fixed the issue of PCam not registering nodes from instantiated scenes. You can grab the fixed update [here](https://github.com/daz-b-like/ProCam2D_Godot4.x/archive/ed9dc6f28d538ff5227306534f001a5e680aeec8.zip). Feel free to report any issues or make any feature requests to help make the plug-in better. Good day!

**Comment by HiIAmBarney** [comment]
@daz-b-like Woah! That was quick!
Plugged it in, seemed to work initially, however when I free the Scene with the Room, PCam now throws an Error: 
"Invalid access to the property or key 'global_position' on a base object of type 'previously freed'."

(This happens with MetSys automatically, but, at least I think, it's a common use case to free Rooms you are no longer in, so this may occur often.)

Debugger points to the following Line: ProCam2D/scripts/core/nds/cam.gd:134 - at function: _get_nearby_nodes

The issue outlined in this thread has technically been resolved, as I did not foresee this issue. 
Edit: 
I will open another issue report.
