### ISSUE TITLE
PCAM Magnet  uses Interpolate instead of Sample function

### ISSUE THREAD

**Issue by HiIAmBarney** [daz-b-like/ProCam2D_Godot4.x#6]
**Describe the bug**
The PCAM Magnet Node still uses the "interpolate" function, which has been replaced in Godot 4 with "sample"

**To Reproduce**
1. Setup a PCAM Magnet.
2. Untick Full Force, so it samples a Curve Object. (Any Curve will produce the error.

**Expected behavior**
To Fix this, simply change this line: (Line 105 in m.gd) "var force_magnitude = force * falloff_curve.interpolate(distance / radius)"
to: "var force_magnitude = force * falloff_curve.sample(distance / radius)".

At least that did it for me.

**Comment by daz-b-like** [comment]
Thanks. I must have missed that when porting the plugin from Godot 3 to 4.
